nelmio_cors:
    defaults:
        allow_origin: ['*']  # Substitua '*' com o domínio do seu frontend em produção
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        allow_credentials: true  # Substitua 'supports_credentials' por 'allow_credentials'

    paths:
        '^/api/':  # Aplica a configuração apenas para as rotas da API
            allow_origin: ['*']  # Permitir todas as origens ou substituir pelo seu domínio frontend
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            allow_credentials: true  # Permite o envio de cookies ou cabeçalhos de autenticação
